# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Divyanshu Shende
tagline:          Homepage
description:      Welcome to divush's Home
baseurl:          /

author:
  name:           Divyanshu Shende
  url:            home.iitk.ac.in/~divush

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
  - jemoji

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/divush

bitbucket:
     repo:        https://bitbucket.org/divyanshu_shende/

emoji_dir:        images/emoji
